# -*- coding: utf-8 -*-
"""Health RAG(Abdullah Asim)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1VRrLVvQH_84FOC2s4n0B-_OILSUyWC
"""

!pip install -q langchain openai faiss-cpu tiktoken langchain_community

import os
os.environ["OPENAI_API_KEY"] = "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"  # 🔐 Replace with your OpenAI API Key

from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS
from langchain.text_splitter import CharacterTextSplitter
from langchain.document_loaders import TextLoader

#  Load sample document (replace with your own file)

with open("health_context.txt", "w") as f:
    f.write(
        """Fever is a common symptom of infection and can indicate the body is fighting off viruses or bacteria.
        Normal body temperature is around 98.6°F (37°C). A fever is generally considered to be a temperature of 100.4°F (38°C) or higher.\n\n
        A sore throat may be caused by viral infections like the common cold or flu, or by bacterial infections like strep throat. Symptoms include pain when swallowing and irritation.\n\n
        Ibuprofen is an over-the-counter anti-inflammatory drug used to reduce fever, pain, and inflammation. It should be taken with food to prevent stomach upset.\n\n
        Coughing helps clear the airways of mucus or irritants. Persistent coughing may be due to asthma, allergies, or respiratory infections.\n\n
        Consult a healthcare provider if symptoms persist longer than a few days or worsen. Always follow dosage guidelines and seek professional advice before taking new medications.
        Sore throat (pharyngitis) can be viral (e.g., rhinovirus, influenza, EBV) or bacterial (commonly group A Streptococcus). Bacterial pharyngitis typically presents with sudden onset, fever, tonsillar exudates, and absence of cough. The Centor Criteria help guide treatment. Rapid antigen detection tests (RADTs) are used for diagnosis. Penicillin or amoxicillin is the first-line treatment for confirmed strep throat."""


    )



# Step 2: Load the context using a TextLoader
from langchain.document_loaders import TextLoader

loader = TextLoader("health_context.txt")
documents = loader.load()


#  Split text
text_splitter = CharacterTextSplitter(chunk_size=300, chunk_overlap=50)
docs = text_splitter.split_documents(documents)

#  Embeddings + FAISS Index
embedding = OpenAIEmbeddings()
db = FAISS.from_documents(docs, embedding)

from langchain.prompts import PromptTemplate

template = """
You are an AI assistant answering based on retrieved knowledge. Use the context to answer accurately.

Context:
{context}

Question:
{question}

Answer:"""

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template=template,
)

from langchain.chains import RetrievalQA
from langchain.chat_models import ChatOpenAI
llm = ChatOpenAI(model_name="gpt-4o-mini", temperature=0)
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=db.as_retriever(),
    chain_type_kwargs={"prompt": prompt},
)

user_input=input()
result = qa_chain.run(user_input)
print("💡 Answer:", result)